### ISSUE TITLE
How to access mysql database used in local deployment

### ISSUE THREAD

**Issue by abhitheawesomecoder** [graphcool/framework#1125]
I can see that local deployment of graphcool framework is using MySql db. Since local deployment doesn't provide console to manage data, I want to know how to access MySql db used by local deployment.

**Comment by kbrandwijk** [comment]
If you do `graphcool local eject`, it shows `export SQL_INTERNAL_DATABASE="graphcool"` in the `.envrc` file, and that's used as database name in the `docker-compose.yml`. So I assume that should work, but haven't tested it.

**Comment by abhitheawesomecoder** [comment]
But I also want to access MySql db being used and be able to run MsSql
command again the database from my local console.

**Comment by abhitheawesomecoder** [comment]
And if possible connect interface like phpmyadmin to the MySql db being
used. So that I can get a console like graphcool cloud server.

**Comment by kbrandwijk** [comment]
You wanted to know the name of the created database. Have you actually tried connecting to it already?

**Comment by abhitheawesomecoder** [comment]
I have no clue where the MySql DB for graphcool reside, after deployment. So, I haven't tried connection

**Comment by Tav0** [comment]
do `docker exec -it <container-mysql-id> sh` then do `mysql -u root -p` and type `graphcool` as password and then use mysql command line. No need for eject.

**Comment by kbrandwijk** [comment]
@Tav0. You are right, you don't need to eject either way. I just ejected to get the username/password and database name from the variables file one time.

**Comment by kbrandwijk** [comment]
Update: running `docker run -d --link local_graphcool-db_1:db --network local_graphcool -p 8080:80 phpmyadmin/phpmyadmin` works beautifully.

**Comment by abhitheawesomecoder** [comment]
@Tav0  and @kbrandwijk you guys are amazing. :+1: 

You made my day. 

But I am curious to know, how you guys found this hidden info

**Comment by kbrandwijk** [comment]
@abhitheawesomecoder it's not hidden information. I have installed Kitematic on Windows, which shows me very nicely which environment variables a docker container uses, and which network it is connected to. So then it's not too hard to figure out the next steps anymore.
![image](https://user-images.githubusercontent.com/852069/32373743-19b564e6-c09b-11e7-9308-9815099cc674.png)

**Comment by abhitheawesomecoder** [comment]
I see. I will also give it a try. Thanks again for all helpful info.

**Comment by nikolasburk** [comment]
I added a section to the docs: https://www.graph.cool/docs/reference/deployment/database-access-eif6eing5o

**Comment by kbrandwijk** [comment]
@nikolasburk I did the same, but with myphpadmin, because it gives you a graphical UI. Would it make sense to add that option to the docs?

**Comment by kbrandwijk** [comment]
@nikolasburk Why did you choose the command-line option, instead of the graphical one?

**Comment by marktani** [comment]
It's easy to transfer the command line option to a 'vendor-specific' graphical one. The opposite might not be the case.

**Comment by steve-a-jones** [comment]
As a workaround I modified the docker-compose.yml to port forward 3306 on the db container.

Are there any caveats with this approach?

 Without cascading deletes (yet ;)) I needed a sane way to wipe db tables during tests..

**Comment by kbrandwijk** [comment]
There's no caveat. I have done the same on the running docker container with Kitematic on Windows. That works fine. But starting an extra docker container on the same network (either with the GUI or command line mysql tools) works better because it requires no modification of anything regarding the Graphcool docker containers.

**Comment by bkniffler** [comment]
Just fyi, I installed the latest version of prisma and I didn't need to change any config, just connected to 3307 with root/graphcool and all fine. I recommend to use Kitematic though (latest releases https://github.com/docker/kitematic/releases), pretty cool for logs, env, etc.

**Comment by sakhmedbayev** [comment]
I just upgraded to Prisma 1.8.

I can successfully connect to mysql running in my `server_mysql_1` container, by using this command:

`docker exec -it server_mysql_1 mysql -u root --host 127.0.0.1 --port 3306 --password=prisma`

but, I cannot connect to any database in Sequel Pro. Here is my settings in Sequel Pro:

host: 127.0.0.1
username: root
password: prisma
database: default@default # can run any command against this database while in terminal
port: 3307 # I have tried 3306

**Comment by sakhmedbayev** [comment]
@tyholby this at the end worked for me:
1. remove your existing prisma sql server container (make sure to backup everything you will need)
2. change `docker-compose.yml` adding port forwarding, like so:
```
mysql:
    ports: 
        - "3306:3306"
```
3. run ` docker-compose up -d`
4. in Sequel Pro, use settings I showed above, the port should be 3306

**Comment by galoi** [comment]
> 2. change docker-compose.yml adding port forwarding, like so:

```
mysql:
    ports: 
        - "3306:3306"
```
↑ is not worked for me:

↓ is worked for me:
```
  mysql:
    ports:
      - '3333:3306'
```

**Comment by priley86** [comment]
any suggestion on how to do this with a config like the following?

```
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.23
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: my-secret
        port: 4466
        databases:
          default:
            connector: mysql
            active: true
            host: prisma-db
            port: 3306
            user: root
            password: prisma
  db:
    container_name: prisma-db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: prisma
```

It does not seem that `port` can be changed to a string underneath the `PRISMA_CONFIG` section.
```
        databases:
          default:
            connector: mysql
            active: true
            host: prisma-db
            ports: 
              - '3306:3306'
```

Error:
```
prisma_1  | Exception in thread "main" java.lang.RuntimeException: Unable to load Prisma config: com.prisma.config.InvalidConfiguration: Expected Int for field port, got <unset>
```

**Comment by priley86** [comment]
ok...resolved this. Just like the notes above, needed to forward to a different port and ensure the `ports` was listed in the db section like so:

```
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.23
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: my-secret
        port: 4466
        databases:
          default:
            connector: mysql
            active: true
            host: prisma-db
            port: 3306
            user: root
            password: prisma
            connectionLimit: 3
  db:
    container_name: prisma-db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: prisma
    ports:
      - '3333:3306'
```
