### ISSUE TITLE
Support resolver types in types.graphql

### ISSUE THREAD

**Issue by sorenbs** [graphcool/framework#543]
Currently the schema for a resolver must be defined in a separate file:

> graphcool.yml

```
functions:
  facebook-authentication:
    handler:
      code:
        src: ./src/facebook-authentication.js
    type: resolver
    schema: ./src/facebook-authentication.graphql
```

> facebook-authentication.graphql

```
type AuthenticateFacebookUserPayload {
  token: String!
}

extend type Mutation {
  authenticateFacebookUser(facebookToken: String!): AuthenticateFacebookUserPayload
}
```

In the future we will keep supporting this setup. Additionally we will support placing all types in the `types.graphql` file:

> types.graphql

```
type FacebookUser @model {
  id: ID! @isUnique
  facebookUserId: String @isUnique
  facebookEmail: String
  createdAt: DateTime!
  updatedAt: DateTime!
}

type AuthenticateFacebookUserPayload {
  token: String!
}

extend type Mutation {
  authenticateFacebookUser(facebookToken: String!): AuthenticateFacebookUserPayload @resolver(handler: "facebook-authentication")
}
```

Also note that we now use the `@model` directive to distinguish between model types that are backed by the database and "free types" that can be used in resolvers

# Rationale

Placing all types in one file makes it easier to reuse payloads between resolvers.

It is still possible to organise your Graphcool application into modules with individual `types.graphql` files
