### ISSUE TITLE
Better project id, especially with usage from CLI

### ISSUE THREAD

**Issue by timsuchanek** [graphcool/framework#576]
Currently we identify a project visually in the Console with the Project Name.
In the CLI however, we're using the project ids, that are not human-readable, so a mapping is hard:

```yaml
default: dev
environments:
  dev: cj7ptsbd210jk0183ec7gvc6c
```

Something like this would be more readable:

```yaml
default: dev
environments:
  dev: app-name-123
```

This could be implemented using the aliases we already have in place.

The only thing blocking us from that currently is that the System API only accepts the project id as the unique identifier and also would need to accept the `alias` as the system api call.

Also we have 2 orthogonal concepts here:
An internal alias and an external alias.
An external alias can make a lot of sense when using `blue/green` deployment.
Then you don't want to mix the internal and external alias, they should be independent, the `alias` as we know it is then only a `deployment detail`, but is not included in the daily workflow.

This is a concrete example stating this issue:

```yaml
default: dev
environments:
  blue: app-name
  green: ?
```

If I now want to first deploy to `green`, run tests against it and then switch to `blue`, it is not intuitive when mixing the `external` alias with an internal alias.

Another solution for this problem would be to include the current Project Name everywhere in the CLI. This, however, would make everything rather messy.

This is an open discussion, feedback & ideas welcome!
