### ISSUE TITLE
Improve "The schema is invalid: Invalid field type definition detected." error message

### ISSUE THREAD

**Issue by resonantfreq** [graphcool/framework#778]
Noticing an issue with the CLI. After I successfully deploy to a production environment for the first time, a second push triggers a schema not found error. Here are the steps to reproduce along with info from debug window. (Note: All this is test data so there should not be any worries on sensitive data.)

1. `graphcool deploy --new-service EmreAuthDev4`
2. `more .graphcoolrc #find the target for the newly created service`
3. `graphcool deploy --target prod1` 

This deployment does have a custom resolver function defined in the YAML file.

**Comment by marktani** [comment]
Could you please share the content of your `graphcool.yml` file? Also, this is the error message:

> The schema is invalid: Invalid field type definition detected. Valid field type formats: Int, Int!, [Int!], [Int!]! for example.

**Comment by resonantfreq** [comment]
```
types: ./types.graphql

functions:
  authConsentUrl:
    handler:
      code:
        src: src/auth/consentUrl.js
    type: resolver
    schema: src/auth/consentUrl.graphql
permissions:
- operation: File.read
- operation: File.create
- operation: File.update
- operation: File.delete
- operation: Profile.read
- operation: Profile.create
- operation: Profile.update
- operation: Profile.delete
- operation: User.read
- operation: User.create
- operation: User.update
- operation: User.delete
- operation: UserProfiles.*
rootTokens:
- vyrlAuthService
```
