### ISSUE TITLE
Deploy gets into endless loop when environment variable not set

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/framework#966]
**Current behavior**
I forgot to set an environment variable. On deploy, the CLI gets into an endless loop that I forcefully had to kill.

![image](https://user-images.githubusercontent.com/852069/31842949-df5b8578-b5f0-11e7-9359-15d7b681f775.png)

**Expected behavior?**
Just one warning would be enough.

**Comment by timsuchanek** [comment]
@kbrandwijk thanks for reporting. Is this still happening for you? I currently can't reproduce it.

**Comment by kbrandwijk** [comment]
@timsuchanek This still happens. Minimal reproduction:
```
functions:
  hello:
    handler:
      webhook: 
        url: ${env:idonotexist}/hello
    type: resolver
    schema: src/hello.graphql
```
Looping output as above that cannot be stopped.
