### ISSUE TITLE
Webtask webhook support

### ISSUE THREAD

**Issue by sorenbs** [graphcool/framework#991]
Creating a simple webhook in webtask:

```js
module.exports = 
    function (cb) {
        cb(null, {data: {name: "My Name!"}
        });
    }
```

and referencing it from graphcool.yml:

```yml
functions:
  hello:
    handler:
      webhook: 
        url: https://wt-graphcool.it.auth0.com/api/run/cinm8a8rn0002fiqco02d1ce9/cj91flpc2000201njyxdnm2j0
    type: resolver
    schema: src/hello.graphql
```

Should work.

What happens now is that when I invoke the hello resolver function, the query to graphcool just times out.
